# Una introducción a Python: Conceptos básicos de programación
**Autor**: Fermín Cruz.   **Revisores**: José A. Troyano, Carlos G. Vallejo, Mariano González, Daniel Mateos.   **Última modificación:** 1 de octubre de 2018

Este documento está pensado para que comiences a comprender los programas escritos en el lenguaje Python, y a escribir tus primeros programas. No tienes que tener ningún conocimiento previo para entenderlo, aunque algunos de los conceptos son un poco abstractos, por lo que es posible que tengas que leer las explicaciones varias veces, y despacito... No pretendemos profundizar en ninguno de los contenidos que aquí se presentan, sino más bien dar un primer vistazo a lo que te puedes encontrar en un programa escrito en Python. Más adelante, iremos profundizando en cada uno de estos contenidos. 


Debes ir ejecutando cada una de las celdas de código\* que vayas encontrado. Para hacer esto, puedes hacer clic en la celda en cuestión y luego en el botón con el icono de "play" que aparece en la barra de herramientas; también puedes pulsar las teclas "Mayúsculas" y "Entrar" al mismo tiempo. Si empiezas en la primera celda, puedes ir usando el mismo icono de "play" para ir ejecutando y avanzando a lo largo del notebook. Si "ejecutas" una celda como esta, que no contiene código, simplemente pasarás a la siguiente. **Debes ejecutar todas las celdas que contienen código**, si no lo haces es posible que algunos ejemplos de código\* no funcionen. 

Los apartados marcados con el título **¡Prueba tú!** están pensados para que escribas pequeños trocitos de código\*, de manera que compruebes si has comprendido lo que se te acaba de explicar. Es importante que no continúes leyendo hasta que no hayas resuelto lo que se te va pidiendo. Si no consigues resolver alguno de estos apartados, ya sabes: **pide ayuda a tu profesor**.

\* Cuando hablamos de "código" nos referimos a un trozo de texto sacado de un programa informático. En inglés, es frecuente usar el término **coding** para referirse al acto de escribir programas informáticos. Por cierto, ¿qué tal andas de inglés? Verás que gran parte de la información que hay que consultar para programar está en inglés, así que es mejor que te vayas acostumbrando...

### ¿Empezamos?

## 1. Instrucciones y funciones

Un programa Python está formado por **instrucciones** (a veces también son llamadas **sentencias**). Cada instrucción se escribe normalmente en una línea. Por ejemplo, la siguiente instrucción sirve para imprimir el mensaje "Hola, mundo!" en la pantalla.

Para ejecutar la instrucción, haz clic sobre la celda de abajo y luego pulsa el icono de "play" (también puedes pulsar las teclas "Mayúsculas+Entrar").

In [1]:
print(5)

5


Si en un programa hay varias instrucciones, estas se ejecutan secuencialmente, una tras otra.

In [2]:
print("Hola, mundo!")
print("Adiós, mundo!")

Hola, mundo!
Adiós, mundo!


La instrucción que hemos usado en los ejemplos anteriores, **print** (que significa imprimir en inglés), es una **función predefinida** (*built-in function*). Una función puede ser "llamada" (también se dice "invocada") desde un programa escribiendo su nombre y a continuación unos paréntesis de apertura y cierre. En ocasiones, las funciones reciben **parámetros**, que se escriben en la llamada dentro de los paréntesis, separados por comas si hay más de uno.

### ¡Prueba tú!

In [3]:
# Escribe una llamada a la función print para mostrar algún mensaje en pantalla.

print("BUenos días")


BUenos días


Hay muchas funciones predefinidas, por ejemplo la función **help** nos proporciona ayuda sobre cualquier otra función. 

In [4]:
help(print)   # Nos muestra información de ayuda sobre la función predefinida print

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



Por supuesto, la ayuda está en inglés. Habrá que acostumbrarse, porque la inmensa mayoría de documentación y ayudas que vas a encontrar para programar estará también en inglés...

### ¡Prueba tú!

In [5]:
# Haz que se muestre la ayuda disponible sobre la propia función help

help(help)

Help on _Helper in module _sitebuiltins object:

class _Helper(builtins.object)
 |  Define the builtin 'help'.
 |  
 |  This is a wrapper around pydoc.help that provides a helpful message
 |  when 'help' is typed at the Python interactive prompt.
 |  
 |  Calling help() at the Python prompt starts an interactive help session.
 |  Calling help(thing) prints help for the python object 'thing'.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args, **kwds)
 |      Call self as a function.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



En el ejemplo anterior hemos usado el carácter almohadilla (#) para escribir un **comentario** sobre el código. Los comentarios se usan en los programas para hacer aclaraciones, explicar el funcionamiento y, en general, hacer más fácil de entender nuestros programas. 

Las funciones anteriores se llaman funciones predefinidas porque ya vienen incluidas "por defecto" en Python. Por contra, los programadores pueden **definir** sus propias **funciones**, como se muestra a continuación.

In [6]:
# ajsks aiays kaha siaua sksua udia idua sjsha 

In [7]:
def saluda(nombre):
    
    #ahahaha 
    '''
    qjqhqvq 
    qjqquq quit
    qqqyq 
    qhqhq
    Esta función imprime un saludo personalizado con el nombre indicado mediante el parámetro "nombre".
    '''
    print("Hola, "+nombre)

In [8]:
saluda("Pepe")

Hola, Pepe


La función que acabamos de definir se llama *saluda* y recibe un único parámetro. Después de la primera línea (llamada **cabecera** o **prototipo** de la función) vienen una o varias instrucciones (llamadas **cuerpo** de la función), que serán ejecutadas cuando alguien llame a la función. Date cuenta de que las instrucciones que conforman el cuerpo de la función aparecen indentadas, es decir, tienen un tabulador delante. 

Las primeras líneas del cuerpo de la función, que comienzan y acaban con tres comillas simples, se llaman **comentario de documentación** de la función, y, aunque no son obligatorias, sí es recomendable incluirlas. Cuando alguien llame a la función predefinida *help* para pedir ayuda sobre nuestra función, se mostrará precisamente el texto aquí incluido.

Lo que hará la función cuando alguien la llame será mostrar un mensaje de saludo. Hagamos una llamada para probar la función: prueba a escribir tu nombre entre las comillas.

In [9]:
saluda("Fermín")

Hola, Fermín


Al definir una función conseguimos reutilizar la funcionalidad implementada las veces que queramos, simplemente llamando a la función en las partes del programa en que necesitemos dicha funcionalidad. Por ejemplo, ahora puedo realizar varios saludos, uno tras otro:

In [10]:
saluda("John")
saluda("Paul")
saluda("George")
saluda("Ringo")

Hola, John
Hola, Paul
Hola, George
Hola, Ringo


### ¡Prueba tú!

Define una función llamada *saluda_educado* que reciba un nombre como parámetro, imprima el mismo saludo personalizado que la función saluda, y a continuación imprima el texto "Encantado de conocerle".

**¡Truco!:** puedes llamar a la función anterior *saluda* desde el cuerpo de la nueva función *saluda_educado*.

In [11]:
def saluda_educado(a):
    saluda(a)
    print("Encantado de conocerle")



In [12]:
saluda_educado("Pepe")

Hola, Pepe
Encantado de conocerle


## 2. Expresiones y tipos

En la instrucción que hemos escrito al definir la función *saluda*:
```python 
print("Hola, " + nombre)
```

hemos usado un **operador**, el signo +, que sirve para concatenar las dos cadenas de texto: la cadena *"Hola, "* y la cadena contenida en el parámetro *nombre*. 

El uso de operadores es habitual en todos los lenguajes de programación. Llamamos **expresiones** a las instrucciones formadas por operadores (como el +), literales (como la cadena *"Hola, "*) y variables (como el parámetro *nombre*) *[bueno, y más participantes que iremos viendo más adelante]*. Una expresión es siempre evaluada por Python, para obtener un resultado, antes de seguir ejecutando el resto de instrucciones del programa. 

Veamos algunos ejemplos de expresiones utilizando los **operadores aritméticos**. Prueba a cambiar los ejemplos que se muestran para experimentar un poco.

In [13]:
3 + 5

8

In [14]:
3 + 5 * 8

43

In [15]:
(3 + 5) * 8

64

In [16]:
(3 + 5) * 8 / 14

4.571428571428571

### ¡Prueba tú!

In [17]:
# Escribe alguna expresión usando operadores aritméticos. Además de los anteriores tienes los siguientes:
# - // % **
print(4**5)
print(5+5)




1024
10


En las expresiones también podemos usar llamadas a funciones, siempre que sean funciones que devuelvan algún resultado. Para que una función devuelva un valor cuando sea invocada, usaremos la instrucción **return** en algún punto del cuerpo de la función (casi siempre, al final del cuerpo de la función). Por ejemplo:

In [18]:
def doble(x):
    return  x * 2

doble(10)

20

In [19]:
type(print(True))

True


NoneType

In [20]:
type(doble(5))

int

In [21]:
doble(10) + 5

25

In [22]:
def saluda_2(nombre):
    return "Hola, "+ nombre

In [23]:
saluda_2("Pepe") + "adsf"

'Hola, Pepeadsf'

In [24]:
type(saluda_2("Pepe"))

str

A veces necesitamos guardar el resultado de una expresión para utilizarlo más adelante en nuestro programa. Para esto se usan las **variables**. 

In [25]:
resultado = (3 + 5) * doble(8)
print(resultado / 5)

25.6


In [26]:
type(resultado/5)

float

Hemos **asignado** a la variable *resultado* el valor de la expresión que hemos escrito a la derecha del carácter igual (=), de manera que más adelante en el programa podremos utilizar ese valor haciendo mención a la variable. A este carácter igual lo llamamos instrucción de **asignación**.

### ¡Prueba tú!

Intenta definir una función de nombre *descuento* que reciba como parámetro un valor y un porcentaje y devuelva el resultado de aplicar el descuento correspondiente al porcentaje sobre el valor indicado.

In [27]:
# Define aquí la función
def descuento(valor, porcentaje):
    porcentaje = porcentaje / 100
    return valor*(1-porcentaje)




In [28]:
descuento(100, 20)

80.0

Cuando la termines de escribir, puedes ejecutar esta prueba:

In [29]:
precio = 200
print("Precio con 10% de descuento:", descuento(precio, 10))

Precio con 10% de descuento: 180.0


En los ejemplos anteriores, hemos utilizado **literales** de tipo **cadena de caracteres** (por ejemplo, *"Hola, mundo!"*) y literales de tipo número **entero** (por ejemplo, *3*, *5* y *8*). Hay más tipos de literales, por ejemplo literales de tipo número **real** o de tipo **lógico**: 

In [30]:
PI = 3.14159
radio = 10
area = PI * radio**2   # El operador ** sirve para calcular potencias
print("El área del círculo es", area)

umbral = 100.0
area_superior_umbral = area > umbral  
# El carácter > es un operador relacional, se evalúa como True (verdadero) o False (falso)
print("¿Es el área superior al umbral?", area_superior_umbral)

El área del círculo es 314.159
¿Es el área superior al umbral? True


## 3. Listas y tuplas

Cuando necesitamos almacenar varios datos en una sola variable, utilizamos literales de tipo **lista**:

In [31]:
temperaturas = [28.5, 27.8, 29.5, 32.1, 30.7, 25.5, 26.0]
print(temperaturas)

[28.5, 27.8, 29.5, 32.1, 30.7, 25.5, 26.0]


In [32]:
heroes = ["Spiderman", "Iron Man", "Lobezno", "Capitán América", "Hulk"]
print(heroes)

['Spiderman', 'Iron Man', 'Lobezno', 'Capitán América', 'Hulk']


O, a veces, de tipo **tupla**, que se escriben igual pero usando paréntesis en lugar de corchetes:

In [33]:
usuario = ("Mark", "Lenders")
print(usuario)

('Mark', 'Lenders')


Ambos, listas y tuplas, se parecen mucho (ya veremos algunas diferencias más adelante). Podemos acceder a un elemento concreto, indicando el **índice** de dicho elemento (es decir, la posición que ocupa dentro de la lista o tupla, contando desde la izquierda):

In [34]:
temperaturas

[28.5, 27.8, 29.5, 32.1, 30.7, 25.5, 26.0]

$x[i]$
$x_i$

En python el primer índice es 0

In [35]:
temperaturas[6]

26.0

In [36]:
temperaturas[0]   # La primera posición corresponde al índice 0

28.5

In [37]:
heroes

['Spiderman', 'Iron Man', 'Lobezno', 'Capitán América', 'Hulk']

In [38]:
heroes[4]

'Hulk'

In [39]:
usuario

('Mark', 'Lenders')

In [40]:
usuario[1]

'Lenders'

In [41]:
temperaturas[1] = 27.0
# Puedo asignar un valor a una posición cualquiera de una lista
print(temperaturas)

[28.5, 27.0, 29.5, 32.1, 30.7, 25.5, 26.0]


In [42]:
temperaturas[0] =  temperaturas[0] + 0.5
# Incrementamos en 0.5 grados la primera temperatura de la lista
print(temperaturas)

[29.0, 27.0, 29.5, 32.1, 30.7, 25.5, 26.0]


También podemos conocer en cualquier momento el número total de elementos dentro de una lista o una tupla mediante la función predefinida **len**:

In [43]:
len(temperaturas)

7

In [44]:
len(usuario)

2

---
**¡Cuidado!** No podemos asignar valores a las posiciones de una tupla. Prueba a ejecutar este código:

In [45]:
usuario[0] = "Marcos" # Cambiemos el nombre del usuario

TypeError: ignored

In [46]:
print(z)

NameError: ignored

Decimos que las tuplas son un **tipo inmutable**, lo que significa que una vez que hemos guardado un valor en una variable de este tipo, ¡ya no podremos cambiarlo!

Lo que acaba de ocurrir es un **error en tiempo de ejecución**. Estos errores ocurren frecuentemente mientras estamos escribiendo y probando nuestros programas, y significan que no hemos hecho algo de la manera correcta. Cuando se produce uno de estos errores, el programa deja de ejecutarse. Cuando nuestro programa esté acabado y bien probado, no debería ocurrir ninguno de estos errores... Aunque ocasionalmente ocurre. Seguro que te suena esta ventana:

![title](img001.png)


### ¡Prueba tú!

Los elementos de la lista *temperaturas* son números reales. Pero una lista puede contener elementos del tipo que quieras. Intenta definir una lista *usuarios*, en la que cada elemento sea una tupla *(nombre, apellido)*, como la tupla *usuario* que hemos definido anteriormente. Aquí tienes algunos pares nombre-apellido que puedes meter en la lista:
* Mark Lenders
* Oliver Atom
* Benji Price

In [47]:
# Completa la instrucción siguiente:
usuarios = [("Mark", "Lenders"), ("Oliver", "Atom"), ("Benji", "Price")]

In [48]:
print(usuarios[0][0] + " " + usuarios[0][1] )

Mark Lenders


In [49]:
a = (1,2,3)
b = (4,5,6)

In [50]:
a+b 

(1, 2, 3, 4, 5, 6)

## 4. Diccionarios

Existen más tipos como las listas y las tuplas, que permiten almacenar conjuntos de datos. Uno muy utilizado es el **diccionario**. En un diccionario, cada valor almacenado se asocia a una clave, de manera que para acceder a los **valores** se utilizan dichas **claves** (de forma parecida a como para acceder a los valores de una lista se utilizan los índices).


Puedes pensar en un diccionario como si se tratara de una tabla con dos columnas. Por ejemplo, un diccionario podría almacenar las temperaturas medias de las capitales andaluzas, indexando dichos valores mediante los nombres de las capitales:

|Clave|Valor|
|---|---|
|"Almería"|19.9|
|"Cádiz"| 19.1|
|"Córdoba"| 19.1|
|"Granada"|16.6|
|"Jaén"|18.2|
|"Huelva"|19.0|
|"Málaga"|19.8|
|"Sevilla"|20.0|

Lo cual se escribiría en Python de la siguiente manera:

In [53]:
temperatura_media = {"Almería": 19.9, "Cádiz": 19.1, "Córdoba": 19.1, "Granada": 16.6, 
                    "Jaén": 18.2, "Huelva": 19.0, "Málaga": 19.8, "Sevilla": 20.0}
print(temperatura_media)

{'Almería': 19.9, 'Cádiz': 19.1, 'Córdoba': 19.1, 'Granada': 16.6, 'Jaén': 18.2, 'Huelva': 19.0, 'Málaga': 19.8, 'Sevilla': 20.0}


Ahora podemos trabajar con los datos del diccionario de forma parecida a las listas, aunque usando las claves para acceder a los valores, en lugar de los índices.

In [54]:
temperatura_media[0] #No existe esta clave

KeyError: ignored

In [55]:
print("Temperatura anterior:", temperatura_media['Sevilla'])
#temperatura_media['Sevilla'] = temperatura_media['Sevilla'] + 1
temperatura_media['Sevilla'] += 1.0   # ¡Cambio climático!
print("Temperatura actual:", temperatura_media['Sevilla'])

Temperatura anterior: 20.0
Temperatura actual: 21.0


### ¡Prueba tú!

Intenta definir un diccionario en el que las claves sean los usuarios que definiste en el ejercicio anterior, y los valores asociados sean las claves de acceso a un sistema.

In [56]:
# Completa la instrucción siguiente:
claves = {usuarios[0]:152637, usuarios[1]:152537, usuarios[2]:352637}

In [57]:
claves[("Mark","Lenders")]

152637

## 5. Objetos

Si queremos añadir un elemento a la lista *temperaturas*, podemos hacerlo así:

[29.0, 27.0, 29.5, 32.1, 30.7, 25.5, 26.0]

In [58]:
temperaturas.append(29.2)  # añade el valor 29.2 al final de la lista
print(temperaturas)
print(len(temperaturas))

[29.0, 27.0, 29.5, 32.1, 30.7, 25.5, 26.0, 29.2]
8


Cuando una variable (*temperaturas*) puede ser usada como en el ejemplo anterior, escribiendo un punto (.) y a continuación invocando a una función (*append*), decimos que la variable es un **objeto**, y a la función en cuestión la llamamos **método**. La principal diferencia entre un método y una función es que el primero sólo se puede llamar si tenemos previamente un objeto del tipo adecuado. Por ejemplo, el método *append* sólo puede ser invocado sobre un objeto de tipo lista. 

Intentemos llamar a *append* como si fuese una función:

In [59]:
append(29.2)

NameError: ignored

Puedes ver todos los métodos que tiene un objeto mediante la función predefinida **dir**:

In [60]:
dir(temperaturas)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

Y si quieres una descripción más detallada de cada método, puedes usar la función **help**, que ya hemos usado anteriormente.

In [61]:
help(temperaturas)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

### ¡Prueba tú!

Intenta utilizar algunos de los métodos del objeto *temperaturas*:

In [62]:
a = temperaturas.pop()




In [63]:
a

29.2

In [64]:
temperaturas

[29.0, 27.0, 29.5, 32.1, 30.7, 25.5, 26.0]

In [65]:
temperaturas.insert(1,29)

In [66]:
temperaturas

[29.0, 29, 27.0, 29.5, 32.1, 30.7, 25.5, 26.0]

In [67]:
insert(1,29)

NameError: ignored

## 6. Control del flujo de ejecución

Podemos utilizar la instrucción **for** para recorrer los elementos de una lista o una tupla. Llamamos a esto un **bucle**.

for nombre_dado_pos_nosotros in iterable:
    acciones a ejecitar

In [68]:
for temperatura in temperaturas:    # Se puede leer así: para cada valor "temperatura" en la lista "temperaturas"
    print("Temperatura:", temperatura)

Temperatura: 29.0
Temperatura: 29
Temperatura: 27.0
Temperatura: 29.5
Temperatura: 32.1
Temperatura: 30.7
Temperatura: 25.5
Temperatura: 26.0


En el código anterior, la instrucción que aparece indentada se ejecuta una vez para cada elemento de la lista *temperaturas*. En cada ejecución, la variable *temperatura* almacena un elemento distinto de la lista, comenzando por el primero y pasando por cada elemento secuencialmente. Date cuenta también de que la función predefinida *print* se puede usar con varios parámetros, en cuyo caso mostrará cada uno de ellos por pantalla.

Veamos otro ejemplo de bucle:

In [69]:
suma = 0
for temperatura in temperaturas:
    suma += temperatura
    #suma = suma + temperatura
    # El operador += almacena en "suma" el resultado de sumar "temperatura" al valor anterior de "suma"
print("La temperatura media en la semana ha sido", suma / len(temperaturas), "grados.")

La temperatura media en la semana ha sido 28.599999999999998 grados.


Aunque realmente no hace falta hacer un bucle para sumar los elementos de una lista, ya que esto mismo podemos hacerlo en Python con la función predefinida **sum**.

In [70]:
print("La temperatura media en la semana ha sido", sum(temperaturas) / len(temperaturas), "grados.")

La temperatura media en la semana ha sido 28.599999999999998 grados.


La instrucción *for* es una instrucción de **control del flujo de ejecución**, pues permite que la secuencia en que se van ejecutando las distintas instrucciones varíe con respecto a la ejecución esperada (recordemos que, por defecto, las instrucciones se van ejecutando una tras otra, en el orden en que las hemos escrito, y una sola vez). Otra instrucción que también altera el flujo normal de ejecución es la instrucción **if**. Veamos un ejemplo:

if sentencia:
    acción
elif sentencia:
    acción
else:
    acción
    
    
    
    

In [71]:
def saluda(nombre, hora):
    if hora < 12:     # Si el parámetro "hora" es menor de 12, se ejecuta el siguiente bloque de instrucciones
        print("Buenos días, " + nombre)
    elif hora < 21:   # En otro caso, si el parámetro "hora" es menor de 21, se ejecuta el siguiente bloque de instrucciones
        print("Buenas tardes, " + nombre)
    else:           # En cualquier otro caso, se ejecuta el siguiente bloque de instrucciones
        print("Buenas noches, " + nombre)

saluda("Fermín", 11)
saluda("Fermín", 16)
saluda("Fermín", 21)


Buenos días, Fermín
Buenas tardes, Fermín
Buenas noches, Fermín


Observa que las **palabras clave** que se usan son **if**, **elif** y **else**, y que a continuación de las dos primeras se escribe una expresión lógica (es decir, una expresión cuyo resultado es de tipo lógico: verdadero o falso). Las instrucciones que aparecen tras la palabra **if** sólo se ejecutan si la expresión correspondiente se evalúa como verdadera. Las instrucciones que aparecen tras la palabra **elif** sólo se ejecutan si no se han ejecutado las anteriores, y si la expresión correspondiente se evalúa como verdadera. Las instrucciones que aparecen tras la palabra **else** sólo se ejecutan si no se han ejecutado ninguna de las anteriores. 

Aquí tienes otros ejemplos:

In [72]:
temperaturas[6] = -1

In [73]:
temperatura_actual = temperaturas[6]
if temperatura_actual < 0:  # Si la temperatura es menor de cero grados
    print("¡Cuidado! Riesgo de congelación.")

¡Cuidado! Riesgo de congelación.


Cuando se utiliza el símbolo "==" estamos comparando valores

In [74]:
1==2

False

In [75]:
a = 3
b = 5

In [76]:
a==b

False

In [77]:
a 

3

In [78]:
b 

5

In [79]:
usuario

('Mark', 'Lenders')

In [80]:
# Si el primer elemento de la tupla "usuario" es igual a "Mark" y el segundo elemento es igual a "Lenders"
if usuario[0] == "Mark" and usuario[1] == "Lenders": 
    print("Hola, Mark. Te estaba esperando.")
else:  # En otro caso
    print("Hola, ¿nos conocemos?")


Hola, Mark. Te estaba esperando.


In [81]:
def acceso_restringido(usuario):
    #Necesitamos ingresar una tupla de dos elementos
    if usuario[0] == "Mark" and usuario[1] == "Lenders": 
        print("Hola, Mark. Te estaba esperando.")
    elif usuario[0] == "Oliver" and usuario[1] == "Atom": 
        print("Hola, Oliver. Te estaba esperando.")
    elif usuario[0] == "Benji" and usuario[1] == "Price": 
        print("Hola, Benji. Te estaba esperando.")
    else:  
        print("Hola, ¿nos conocemos?")


In [82]:
acceso_restringido(["sjsjgsbj", 2, 3.4])

Hola, ¿nos conocemos?


Para escribir las expresiones lógicas se usan distintos **operadores lógicos** (como el operador **and**) y **operadores relacionales** (como los operadores **>** o **==**). Iremos viendo más operadores de estos tipos a medida que los vayamos necesitando.

In [83]:
3<=3

True

In [84]:
4>=4

True

In [85]:
4<4

False

In [86]:
4>4

False

In [87]:
5==6

False

In [88]:
if 6<5 and 5<6:
    print("Hola")

In [89]:
if 6<5 or 7<6:
    print("Hola")

### ¡Prueba tú!

Escribe un bucle *for* para llamar a la función *acceso_restringido* pasándole cada uno de los elementos de la lista *usuarios*.

In [90]:
usuarios

[('Mark', 'Lenders'), ('Oliver', 'Atom'), ('Benji', 'Price')]

In [91]:
for j in usuarios:
    acceso_restringido(j)

Hola, Mark. Te estaba esperando.
Hola, Oliver. Te estaba esperando.
Hola, Benji. Te estaba esperando.


In [92]:
suma = 0

In [93]:
for i in range(1,11):
    suma = i + suma
    # suma = suma +i

In [94]:
suma

55

## 7. Módulos y paquetes

Además de las funciones predefinidas, hay muchas otras cosas que se pueden hacer con Python sin necesidad de implementar nosotros ninguna función ni tener que descargar o instalar nada en el ordenador. Eso sí, para poder hacer uso de estas funcionalidades incluidas en Python, es necesario **importar** el módulo o módulos donde están implementadas. Un **módulo** es cada uno de los ficheros con extensión .py en los que están escritos los programas en Python. Los módulos están agrupados en **paquetes**, que son parecidos a las carpetas del explorador de archivos de Windows.

Por ejemplo, si queremos generar números aleatorios, podemos usar el módulo **random**. Antes de hacerlo, es necesario importarlo. Prueba a ejecutar varias veces el siguiente código y verás como cada vez se genera un número distinto:

In [95]:
import random

print(random.randint(1, 100))

95


Fíjate que para llamar a la función randint, que está definida dentro del módulo random, debemos escribir *random.randint(...)*. Si vamos a usar muy a menudo la función en nuestro código, también podemos importarla así:

In [96]:
from random import randint

print(randint(1, 10))

10


De esta manera ya no es necesario indicar la ubicación de la función cada vez que la llamemos. Aunque es más cómodo, no es del todo recomendable, como veremos más adelante.

¿Y si queremos generar, pongamos, 20 números aleatorios, entre 1 y 10? Podemos hacerlo con la instrucción **for**, la misma que utilizamos antes para recorrer los elementos de una lista:

In [97]:
numeros = []
for i in range(20):  # la función predefinida "range" devuelve los números enteros del 0 al 19.
    numeros.append(randint(1, 10))
print(numeros)

[10, 7, 10, 9, 1, 5, 8, 3, 6, 4, 6, 9, 4, 10, 7, 1, 8, 9, 8, 9]


In [98]:
import random as rd

In [99]:
rd.randint(1,98)

1

En el siguiente ejemplo, usamos el módulo *datetime*, que nos permite, entre otras cosas, saber la hora actual en que se está ejecutando el programa.

In [100]:
# El módulo se llama "datetime", y dentro hay definido un objeto que también se llama "datetime"
from datetime import datetime
hora_actual = datetime.now()  # El método now() devuelve un objeto de tipo datetime
# El objeto hora_actual tiene un atributo hour que indica la hora actual (de 0 a 23)
saluda("Fermín", hora_actual.hour)

Buenos días, Fermín


In [101]:
print(hora_actual.minute)

4


In [102]:
help(datetime)

Help on class datetime in module datetime:

class datetime(date)
 |  datetime(year, month, day[, hour[, minute[, second[, microsecond[,tzinfo]]]]])
 |  
 |  The year, month and day arguments are required. tzinfo may be None, or an
 |  instance of a tzinfo subclass. The remaining arguments may be ints.
 |  
 |  Method resolution order:
 |      datetime
 |      date
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __radd__(self, value

In [103]:
print(hora_actual.hour)

2


En el ejemplo anterior, cuando escribimos *hora_actual.hour* estamos accediendo a un **atributo**, llamado *hour*, del objeto *hora_actual*. Por tanto, los objetos tienen, además de métodos, atributos, los cuales son parecidos a las variables (al igual que los métodos eran parecidos a las funciones). La manera de diferenciar si estamos accediendo a un atributo o llamando a un método es que en el segundo caso usamos los paréntesis.

Con los distintos módulos existentes para Python se puede hacer prácticamente de todo. Por ejemplo, dibujar gráficas de todo tipo, mediante la librería **matplotlib**. Cuando hablamos de una **librería** nos referimos a un conjunto de módulos relacionados entre sí por el tipo de funcionalidad que ofrecen. Generalmente, los módulos de una librería están agrupados dentro de un paquete, como es el caso de *matplotlib*.

In [104]:
# Para que las gráficas se muestren sobre el propio notebook, en lugar de en una ventana, hay que escribir:
%matplotlib notebook    

from matplotlib import pyplot  # pyplot es el módulo que permite dibujar gráficas matemáticas

x = []   # "x" es una lista vacía, es decir, aún no contiene elementos
y = []   # "y" también es una lista vacía
for i in range(20):
    x.append(randint(-50, 50))
    y.append(randint(-50, 50))

# El tercer parámetro sirve para especificar el formato de la representación gráfica de los datos
pyplot.scatter(x, y)
pyplot.xlabel("X")
pyplot.ylabel("Y")
pyplot.title("Gráfica de prueba")


<IPython.core.display.Javascript object>

Text(0.5, 1.0, 'Gráfica de prueba')

Todos los paquetes, módulos y librerías más usados están ampliamente documentados en Internet: sólo tienes que hacer una consulta a tu buscador favorito. Por ejemplo, si quieres ver qué otras cosas se pueden hacer con la función *plot*, puedes verlo aquí: https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.plot

### ¡Prueba tú!

Intenta completar el siguiente código para mostrar una gráfica de la función coseno para los valores de la x contenidos en el intervalo \[-10,10\]. Busca documentación sobre el módulo **math** para ver cómo calcular el coseno de un número [prueba buscando en Google "math Python 3"](https://www.google.es/search?q=math+Python+3).

In [105]:
%matplotlib notebook    
import math

lista_x = []  # En esta lista guardaremos los valores para los que vamos a calcular el coseno
for i in range(-100, 101):
    lista_x.append(i/10) # ESCRIBE AQUÍ una instrucción para "añadir a lista_x el valor i / 10"
    
lista_y = []  # En esta lista guardaremos los cosenos de los valores anteriores
for x in lista_x:
    lista_y.append(math.cos(x)) # ESCRIBE AQUÍ una instrucción para "añadir a lista_y el valor coseno(x)"
    

# ESCRIBE AQUÍ una instrucción para dibujar la gráfica correspondiente a las coordenadas lista_x y lista_y.
# Elige las opciones de formato de la representación gráfica que quieras
pyplot.plot(lista_x,lista_y, color="red")




<IPython.core.display.Javascript object>

Cuando construimos una lista a partir de otra, como ocurre con *lista_y* en el código que acabas de completar, podemos hacerlo de una forma muy compacta llamada **definición de listas por comprensión**. Observa el siguiente ejemplo:

lista = [f(i) for i in otra_lista]

In [106]:
lista_y = [math.cos(x) for x in lista_x]
print(lista_y)

[-0.8390715290764524, -0.8891911526253609, -0.9304262721047533, -0.9623648798313102, -0.984687855794127, -0.9971721561963784, -0.9996930420352065, -0.9922253254526034, -0.9748436214041636, -0.9477216021311119, -0.9111302618846769, -0.8654352092411123, -0.811093014061656, -0.7486466455973987, -0.6787200473200125, -0.6020119026848236, -0.5192886541166856, -0.4313768449706208, -0.3391548609838345, -0.2435441537357911, -0.14550003380861354, -0.04600212563953695, 0.05395542056264975, 0.15337386203786435, 0.2512598425822557, 0.3466353178350258, 0.43854732757439036, 0.5260775173811053, 0.6083513145322546, 0.6845466664428066, 0.7539022543433046, 0.8157251001253568, 0.8693974903498253, 0.9143831482353194, 0.9502325919585296, 0.9765876257280235, 0.9931849187581926, 0.9998586363834151, 0.9965420970232175, 0.9832684384425845, 0.960170286650366, 0.9274784307440359, 0.8855195169413189, 0.8347127848391598, 0.7755658785102496, 0.70866977429126, 0.6346928759426347, 0.5543743361791608, 0.468516671300377

In [107]:
lista = [i for i in range(20)]

In [108]:
lista 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

## 8. Ficheros

Es muy habitual trabajar con **ficheros** (quizás estés acostumbrado a referirte a ellos como "archivos", que es un sinónimo). Aunque los ficheros pueden contener todo tipo de datos, nosotros trabajaremos con ficheros de texto. Al igual que haces tú mismo cuando quieres trabajar con un documento en el ordenador, para trabajar con un fichero en Python primero tenemos que abrirlo; después podemos leer o escribir datos en el mismo, y finalmente hemos de cerrarlo. Aquí tienes un pequeño ejemplo que abre un fichero de texto y muestra su contenido en pantalla:


In [109]:
with open("prueba.txt") as f:
    for linea in f:
        print(linea)

# El archivo se cierra automáticamente cuando acaban las instrucciones escritas dentro de la instrucción "with"

FileNotFoundError: ignored

Si el código anterior ocasiona un error al ser ejecutado, asegúrate de que tienes el archivo *prueba.txt* en la misma carpeta desde la que estás ejecutando este notebook.

También es posible que al ejecutar Python te devuelva un "error de codificación", o que te muestre el contenido del fichero de texto con algunos errores (algunos caracteres aparecen de manera extraña). Esto ocurre porque existen múltiples maneras de representar los caracteres de un fichero de texto en notación binaria. Es lo que se conoce como **codificación de caracteres**. Cada sistema operativo tiene su codificación por defecto, de manera que las líneas que acabamos de escribir para leer un fichero de texto dan por hecho que el fichero de texto está expresado en dicha codificación por defecto (la cuál puede no ser la correcta en tu caso). Para evitar estos problemas, siempre que trabajemos con ficheros de texto en la asignatura estableceremos que los ficheros de texto estén en codificación **UTF-8**. Esto se consigue añadiendo un parámetro a la función open:

In [110]:
with open("prueba.txt", encoding='utf-8') as f:
    for linea in f:
        print(linea)

# El archivo se cierra automáticamente cuando acaban las instrucciones escritas dentro de la instrucción "with"

FileNotFoundError: ignored

## 9. Función principal

Cuando escribimos nuestro código en un fichero de texto con extensión ".py", estamos definiendo un módulo. Otros programadores podrán importar nuestro módulo, y hacer uso en sus programas de las funciones que hayamos definido en el mismo, o de las variables y objetos que aparezcan definidos sin indentar.

Sin embargo, algunas veces queremos que el código que hemos escrito sea ejecutado por un usuario; es decir, estamos definiendo un **programa ejecutable**. En este caso, el usuario puede ejecutar el programa con el siguiente comando, escrito desde el **terminal** o **ventana de comandos** del sistema operativo:

<pre>
python nombre_fichero.py
</pre>

Cuando un programa es ejecutable, debe existir un **punto de entrada**. Un punto de entrada es un conjunto de instrucciones que se ejecutarán cuando se lance el programa. En Python, estas instrucciones se deben escribir dentro de un bloque **if** como el que se muestra a continuación:

In [ ]:
if __name__ == '__main__':
    # Aquí vienen las instrucciones que definen el punto de entrada del programa
    hora_actual = datetime.now() 
    saluda("Fermín", hora_actual.hour)
    

Buenos días, Fermín


A veces, el conjunto de instrucciones que definen el punto de entrada se escribe dentro de una función, a la que se le suele dar el nombre **main**. Esto en Python no es obligatorio, aunque sí lo es en otros lenguajes de programación. Si queremos hacerlo así, entonces el programa ejecutable anterior quedaría como sigue (se muestra a continuación el programa completo, con las sentencias *import* y las definiciones de funciones necesarias):


In [ ]:
from datetime import datetime


def main():
    hora_actual = datetime.now() 
    saluda("Fermín", hora_actual.hour)


def saluda(nombre, hora):
    if hora < 12:     # Si el parámetro "hora" es menor de 12, se ejecuta el siguiente bloque de instrucciones
        print("Buenos días, " + nombre)
    elif hora < 21:   # En otro caso, si el parámetro "hora" es menor de 21, se ejecuta el siguiente bloque de instrucciones
        print("Buenas tardes, " + nombre)
    else:           # En cualquier otro caso, se ejecuta el siguiente bloque de instrucciones
        print("Buenas noches, " + nombre)


if __name__ == '__main__':
    main()
 

Buenos días, Fermín


### ¡Prueba tú!

Escribe el código anterior en un fichero de texto llamado "saluda.py", y trata de ejecutarlo desde el terminal o ventana de comandos de tu sistema operativo.

---

Ya sabes lo básico para entender programas simples escritos en Python y para escribir los tuyos propios. **¡Feliz programación!**

In [ ]:
# ¿Conoces el "Zen de Python"?
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Numpy
Numpy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

Importar la paquetería NUMPY

In [ ]:
import numpy as np

Vamos a crear arrays de numpy que son los "vectores"

In [ ]:
vector_1 = np.array([1,2,3,4,5])

In [ ]:
vector_1

array([1, 2, 3, 4, 5])

In [ ]:
vector_2 = np.array([4,5,6,7,8])

In [ ]:
vector_2

array([4, 5, 6, 7, 8])

In [ ]:
vector_1+vector_2

array([ 5,  7,  9, 11, 13])

In [ ]:
vector_1*vector_2

array([ 4, 10, 18, 28, 40])

In [ ]:
np.exp(vector_1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
np.cos(vector_1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

¿Como definir una matriz?

In [ ]:
matriz = np.array([[1,2],[3,4]])

1 2

3 4

In [ ]:
matriz.shape

(2, 2)

In [ ]:
matriz[0][1]

2

In [ ]:
matriz + matriz 

array([[2, 4],
       [6, 8]])

In [ ]:
2*matriz

array([[2, 4],
       [6, 8]])

In [ ]:
3+matriz

array([[4, 5],
       [6, 7]])

In [ ]:
matriz*matriz

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
matriz@matriz

array([[ 7, 10],
       [15, 22]])

In [ ]:
np.matmul(matriz, matriz)

array([[ 7, 10],
       [15, 22]])

Resolvamos el siguiente sistema de ecuaciones:

$$2x-3y=5$$
$$x+y = 10$$

In [ ]:
A = np.array([[2,-3],[1,1]])

In [ ]:
y = np.array([[5],[10]])

In [ ]:
y.shape

(2, 1)

In [ ]:
np.linalg.inv(A)@y

array([[7.],
       [3.]])